config/routes.rb
Rails.application.routes.draw do
  get 'lists/index'
  get 'lists/show'
  get 'lists/new'
  get 'lists/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only:[:index, :show, :new, :create] do
    member do
    resources :bookmarks, only: [:index, :new, :create]
    end
  end
    delete "bookmarks/:id", to: "bookmarks#destroy"
  # resources :movies

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }

  belongs_to :movie
  belongs_to :list


end

app/models/list.rb
class List < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :restrict_with_error

end

app/models/movie.rb
class Movie < ApplicationRecord
  validates  :title, presence: true, uniqueness: true
  validates :overview, presence: true
  validates :poster_url, presence: true, allow_blank: false
  has_many :bookmarks, dependent: :restrict_with_error

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list =List.new
  end

  def create
    @list =List.create(list_params)
  end


  def show
    @list = List.find_by(id: params[:id])
    @bookmarks = Bookmark.select { |bookmark| bookmark.list_id == @list.id}
    if !@bookmarks.empty?
      @movies = []
      @bookmarks.each do |b|
        @movies << Movie.select { |movie| movie.id == b.movie_id}
      end
    else
      @movies = []
      @bookmarks.each do |b|
        @movies << Movie.select { |movie| movie.id == b.movie_id}
      end
    end
  end
  private

  def list_params
    params.require(:list).permit(:name, :photo)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
  <nav class="navbar navbar-light bg-light justify-content-between">
  <a class="navbar-brand" href="#">
    <img src="https://png.pngtree.com/element_our/20190531/ourlarge/pngtree-film-festival-logo-popcorn-and-film-free-png-image_1311154.jpg" width="100" height="100" class="d-inline-block align-top" alt="">

    <nav class="navbar navbar-expand-sm float-right">

    <nav class="navbar navbar-light bg-light ">
    <form class="form-inline">

    <button type="button" class="btn btn-link">My list</button>
    <button type="button" class="btn btn-link">New list</button>

  </a>
  </nav>
  </form>
  </nav>
</div>


    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<%#

<div class="card" style="width: 100%; height: 400px; background-image: url('https://retourverslecinema.com/wp-content/uploads/2015/07/couv-meilleures-places.png') ;">

  <div class="card-body d-flex flex-column justify-content-center align-items-center">
    <p class="card-text text-light display-4">Save any kind of movies.</p>
       <p class="card-text text-light display-6">Classic</p>
  </div>
</div>


<div class="contenair">
<div id="films" class="My Lists">
<h1>My Lists</h1>

<nav class="navbar navbar-expand-sm float-right">

 <nav class="navbar navbar-light bg-light ">
    <form class="form-inline">

<button type="button" class="btn btn-success btn-sm">Create a movie list</button>


</form>
</nav>
</nav>

<div>
  <img style="width: 200px heigth: 50px" src="https://www.universalpictures.fr/tl_files/content/movies/fast9/posters/03.jpg">

</div>

<div>
  <img style="width: 200px heigth: 100px" src="https://musicart.xboxlive.com/7/6e5b6500-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080">

</div>

<div>
  <img style="width: 200px heigth: 100px" src="https://play-lh.googleusercontent.com/UEvkRrEufOxzoAAW29X08EjSKsfqQ4g6l96QZ9198r9NmDckNgT5w8K_YpFdcBd_-kbD2s0Ngs-FiOS7h0cu">

</div>


</div>
</div> %>


<div class="index-bg text-white d-flex flex-column justify-content-center align-items-center">
  <h1>Save any kind of movies</h1>
  <p>Classic</p>
</div>
<div class="d-flex justify-content-end" style="margin: 50px 50px 0 0">
  <%= link_to "Add a movie list",  new_list_path, class: "btn btn-success"%>
</div>
<div class="d-flex flex-column justify-content-center align-items-center" style="margin: 0px 100px;">
  <h2>My Lists</h2>
  <div class="m-4 row">
    <%@lists.each do |list|%>
      <div class="col-2 list-card shadow border rounded-4 d-flex justify-content-center align-items-center m-4">
        <%=cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
        <%=link_to list.name, list_path(list), class: "text-light text-decoration-none"%>
      </div>
    <%end%>
    
  <div class="m-4 d-flex flex-row">
    <% if @lists.empty?%>
      <p>You don't have any list. Let's create one !</p>
    <% else %>
      <%@lists.each do |list|%>
        <a href="<%=list_path(list)%>" class="text-decoration-none">
          <div class="card-category"
              style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
            <%=list.name%>
          </div>
        </a>
      <%end%>
    <% end%>
  </div>
</div>

app/views/lists/new.html.erb
<%# <h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p> %>

<div class="card bg-light shadow" style="width: 50%; margin: auto; padding: 50px; margin-top: 50px">
  <%= simple_form_for @list do |l|%>
    <%= l.input :name%>
    <%= l.input :photo, as: :file %>
    <%= l.button :submit, class: "btn btn-success"%>
  <%end%>
</div>

app/views/lists/show.html.erb
<%# <h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p> %>

      <p>The list is empty !</p>
    <% else%>
      <div class="container">
        <div class="row">
          <%@list.movies.each do |movie|%>
            <div class="card m-4 shadow col-3" style="width: 18rem;">
              <img class="card-img-top" src="<%=movie.poster_url%>" alt="Card image cap" style="height: 200px; object-fit: cover">
        <%@list.movies.each do |movie|%>
          <div class="d-flex flex-row justify-content-between">
            <div class="card shadow col-3" style="width: 18rem;">
              <img class="card-img-top mt-2" src="<%=movie.poster_url%>" alt="Card image cap" style="height: 200px; object-fit: cover">
              <div class="card-body">
                <h3><%= movie.title%></h3>
                <p class="card-text"><%= movie.overview%></p>
                <div class="text-end">
                  <p>Rating: <%= movie.rating %> <i class="fa-solid fa-star text-warning"></i></p>
                </div>
                <h3><%= movie.title %></h3>
                <p class="card-text"><%= movie.overview %></p>
              </div>
            </div>
          <%end%>
        </div>
            <div style="width: 40%">
              <h4>Reviews : </h4>
              <ul class="list-group" >
                <li class="list-group-item"><%=@list.bookmarks[@list.movies.index(movie)].comment%></li>

              </ul>
            </div>
          </div>
        <%end%>
      </div>
    <%end%>
  </div>